apiVersion: networking.k8s.io/v1beta1 # for versions before 1.14 use extensions/v1beta1
kind: Ingress
metadata:
  name: sabnzbd
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: sabnzbd.k8s.fingerguns.club
    http:
      paths:
      - path: /
        backend:
          serviceName: sabnzbd
          servicePort: 8080